default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: riq_development

test:
  <<: *default
  database: riq_test

production:
  <<: *default
  database: riq_production
  username: deploy
  password: <%= ENV['RIQ_DATABASE_PASSWORD'] %>
